apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: fastfood-customer
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: fastfood-api-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fastfood-customer-secret
  namespace: fastfood-customer
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: fastfood-customer-secrets # Este é o nome do Secret que será criado no Kubernetes
    template:
      data:
        DATASOURCE_USERNAME: "{{ .username }}"
        DATASOURCE_PASSWORD: "{{ .password }}"
  dataFrom:
  - extract:
      key: arn:aws:secretsmanager:us-east-1:239409137076:secret:rds!db-fe0086ab-97dd-469b-ae28-ff533b370552